### ISSUE TITLE
why the newly published post doesn't appear in the homepage?

### ISSUE THREAD

**Issue by luckypoem** [jakubfijalkowski/codinginfinity#1]
hi.

i published a post: http://ci.bright.biz.st/posts/2017-01-31-test-1.html ,but why it doesn't appear in the homepage??

and how to transform http://ci.bright.biz.st/posts/2016-08-29-fake_your_way_part2 to
http://ci.bright.biz.st/post/2016-08-29/fake_your_way_part2??

TKS

**Comment by jakubfijalkowski** [comment]
a) This works from here:
![screenshot from 2017-02-02 11-06-22](https://cloud.githubusercontent.com/assets/357096/22545209/1adcd632-e938-11e6-9711-6e47a092f4df.png)

b) Hakyll docs + [this line in Site.hs](https://github.com/jakubfijalkowski/codinginfinity/blob/master/src/Site.hs#L57)

May I ask what are you trying to achieve?
